# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`
# Cross-platform: formula only (safe on WSL/Linux)

brew 'antidote'
brew 'gh'
brew 'git-town'
brew 'glab'
brew 'glow'
brew 'powerlevel10k'
brew 'ranger'
